
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ActiveDirectoryFaultFault", targetNamespace = "urn:internalvim25")
public class ActiveDirectoryFaultFaultMsg extends Exception {

    private com.vmware.vim25.ActiveDirectoryFault faultInfo;

    public ActiveDirectoryFaultFaultMsg() {
        super();
    }

    public ActiveDirectoryFaultFaultMsg(String message) {
        super(message);
    }

    public ActiveDirectoryFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ActiveDirectoryFaultFaultMsg(String message, com.vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault) {
        super(message);
        this.faultInfo = activeDirectoryFaultFault;
    }

    public ActiveDirectoryFaultFaultMsg(String message, com.vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = activeDirectoryFaultFault;
    }

    public com.vmware.vim25.ActiveDirectoryFault getFaultInfo() {
        return this.faultInfo;
    }
}
