
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "AlreadyExistsFault", targetNamespace = "urn:internalvim25")
public class AlreadyExistsFaultMsg extends Exception {

    private com.vmware.vim25.AlreadyExists faultInfo;

    public AlreadyExistsFaultMsg() {
        super();
    }

    public AlreadyExistsFaultMsg(String message) {
        super(message);
    }

    public AlreadyExistsFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistsFaultMsg(String message, com.vmware.vim25.AlreadyExists alreadyExistsFault) {
        super(message);
        this.faultInfo = alreadyExistsFault;
    }

    public AlreadyExistsFaultMsg(String message, com.vmware.vim25.AlreadyExists alreadyExistsFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = alreadyExistsFault;
    }

    public com.vmware.vim25.AlreadyExists getFaultInfo() {
        return this.faultInfo;
    }
}
