
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "AlreadyUpgradedFault", targetNamespace = "urn:internalvim25")
public class AlreadyUpgradedFaultMsg extends Exception {

    private com.vmware.vim25.AlreadyUpgraded faultInfo;

    public AlreadyUpgradedFaultMsg() {
        super();
    }

    public AlreadyUpgradedFaultMsg(String message) {
        super(message);
    }

    public AlreadyUpgradedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AlreadyUpgradedFaultMsg(String message, com.vmware.vim25.AlreadyUpgraded alreadyUpgradedFault) {
        super(message);
        this.faultInfo = alreadyUpgradedFault;
    }

    public AlreadyUpgradedFaultMsg(String message, com.vmware.vim25.AlreadyUpgraded alreadyUpgradedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = alreadyUpgradedFault;
    }

    public com.vmware.vim25.AlreadyUpgraded getFaultInfo() {
        return this.faultInfo;
    }
}
