
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "AnswerFileUpdateFailedFault", targetNamespace = "urn:internalvim25")
public class AnswerFileUpdateFailedFaultMsg extends Exception {

    private com.vmware.vim25.AnswerFileUpdateFailed faultInfo;

    public AnswerFileUpdateFailedFaultMsg() {
        super();
    }

    public AnswerFileUpdateFailedFaultMsg(String message) {
        super(message);
    }

    public AnswerFileUpdateFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AnswerFileUpdateFailedFaultMsg(String message, com.vmware.vim25.AnswerFileUpdateFailed answerFileUpdateFailedFault) {
        super(message);
        this.faultInfo = answerFileUpdateFailedFault;
    }

    public AnswerFileUpdateFailedFaultMsg(String message, com.vmware.vim25.AnswerFileUpdateFailed answerFileUpdateFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = answerFileUpdateFailedFault;
    }

    public com.vmware.vim25.AnswerFileUpdateFailed getFaultInfo() {
        return this.faultInfo;
    }
}
