
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "AuthMinimumAdminPermissionFault", targetNamespace = "urn:internalvim25")
public class AuthMinimumAdminPermissionFaultMsg extends Exception {

    private com.vmware.vim25.AuthMinimumAdminPermission faultInfo;

    public AuthMinimumAdminPermissionFaultMsg() {
        super();
    }

    public AuthMinimumAdminPermissionFaultMsg(String message) {
        super(message);
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, com.vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault) {
        super(message);
        this.faultInfo = authMinimumAdminPermissionFault;
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, com.vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = authMinimumAdminPermissionFault;
    }

    public com.vmware.vim25.AuthMinimumAdminPermission getFaultInfo() {
        return this.faultInfo;
    }
}
