
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "BackupBlobWriteFailureFault", targetNamespace = "urn:internalvim25")
public class BackupBlobWriteFailureFaultMsg extends Exception {

    private com.vmware.vim25.BackupBlobWriteFailure faultInfo;

    public BackupBlobWriteFailureFaultMsg() {
        super();
    }

    public BackupBlobWriteFailureFaultMsg(String message) {
        super(message);
    }

    public BackupBlobWriteFailureFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BackupBlobWriteFailureFaultMsg(String message, com.vmware.vim25.BackupBlobWriteFailure backupBlobWriteFailureFault) {
        super(message);
        this.faultInfo = backupBlobWriteFailureFault;
    }

    public BackupBlobWriteFailureFaultMsg(String message, com.vmware.vim25.BackupBlobWriteFailure backupBlobWriteFailureFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = backupBlobWriteFailureFault;
    }

    public com.vmware.vim25.BackupBlobWriteFailure getFaultInfo() {
        return this.faultInfo;
    }
}
