
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "CannotAccessLocalSourceFault", targetNamespace = "urn:internalvim25")
public class CannotAccessLocalSourceFaultMsg extends Exception {

    private com.vmware.vim25.CannotAccessLocalSource faultInfo;

    public CannotAccessLocalSourceFaultMsg() {
        super();
    }

    public CannotAccessLocalSourceFaultMsg(String message) {
        super(message);
    }

    public CannotAccessLocalSourceFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CannotAccessLocalSourceFaultMsg(String message, com.vmware.vim25.CannotAccessLocalSource cannotAccessLocalSourceFault) {
        super(message);
        this.faultInfo = cannotAccessLocalSourceFault;
    }

    public CannotAccessLocalSourceFaultMsg(String message, com.vmware.vim25.CannotAccessLocalSource cannotAccessLocalSourceFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = cannotAccessLocalSourceFault;
    }

    public com.vmware.vim25.CannotAccessLocalSource getFaultInfo() {
        return this.faultInfo;
    }
}
