
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "CannotAccessFileFault", targetNamespace = "urn:internalvim25")
public class CannotAccessFileFaultMsg extends Exception {

    private com.vmware.vim25.CannotAccessFile faultInfo;

    public CannotAccessFileFaultMsg() {
        super();
    }

    public CannotAccessFileFaultMsg(String message) {
        super(message);
    }

    public CannotAccessFileFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CannotAccessFileFaultMsg(String message, com.vmware.vim25.CannotAccessFile cannotAccessFileFault) {
        super(message);
        this.faultInfo = cannotAccessFileFault;
    }

    public CannotAccessFileFaultMsg(String message, com.vmware.vim25.CannotAccessFile cannotAccessFileFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = cannotAccessFileFault;
    }

    public com.vmware.vim25.CannotAccessFile getFaultInfo() {
        return this.faultInfo;
    }
}
