
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "CannotCreateFileFault", targetNamespace = "urn:internalvim25")
public class CannotCreateFileFaultMsg extends Exception {

    private com.vmware.vim25.CannotCreateFile faultInfo;

    public CannotCreateFileFaultMsg() {
        super();
    }

    public CannotCreateFileFaultMsg(String message) {
        super(message);
    }

    public CannotCreateFileFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CannotCreateFileFaultMsg(String message, com.vmware.vim25.CannotCreateFile cannotCreateFileFault) {
        super(message);
        this.faultInfo = cannotCreateFileFault;
    }

    public CannotCreateFileFaultMsg(String message, com.vmware.vim25.CannotCreateFile cannotCreateFileFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = cannotCreateFileFault;
    }

    public com.vmware.vim25.CannotCreateFile getFaultInfo() {
        return this.faultInfo;
    }
}
