
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ConcurrentAccessFault", targetNamespace = "urn:internalvim25")
public class ConcurrentAccessFaultMsg extends Exception {

    private com.vmware.vim25.ConcurrentAccess faultInfo;

    public ConcurrentAccessFaultMsg() {
        super();
    }

    public ConcurrentAccessFaultMsg(String message) {
        super(message);
    }

    public ConcurrentAccessFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ConcurrentAccessFaultMsg(String message, com.vmware.vim25.ConcurrentAccess concurrentAccessFault) {
        super(message);
        this.faultInfo = concurrentAccessFault;
    }

    public ConcurrentAccessFaultMsg(String message, com.vmware.vim25.ConcurrentAccess concurrentAccessFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = concurrentAccessFault;
    }

    public com.vmware.vim25.ConcurrentAccess getFaultInfo() {
        return this.faultInfo;
    }
}
