
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ConflictingConfigurationFault", targetNamespace = "urn:internalvim25")
public class ConflictingConfigurationFaultMsg extends Exception {

    private com.vmware.vim25.ConflictingConfiguration faultInfo;

    public ConflictingConfigurationFaultMsg() {
        super();
    }

    public ConflictingConfigurationFaultMsg(String message) {
        super(message);
    }

    public ConflictingConfigurationFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ConflictingConfigurationFaultMsg(String message, com.vmware.vim25.ConflictingConfiguration conflictingConfigurationFault) {
        super(message);
        this.faultInfo = conflictingConfigurationFault;
    }

    public ConflictingConfigurationFaultMsg(String message, com.vmware.vim25.ConflictingConfiguration conflictingConfigurationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = conflictingConfigurationFault;
    }

    public com.vmware.vim25.ConflictingConfiguration getFaultInfo() {
        return this.faultInfo;
    }
}
