
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "CustomizationFaultFault", targetNamespace = "urn:internalvim25")
public class CustomizationFaultFaultMsg extends Exception {

    private com.vmware.vim25.CustomizationFault faultInfo;

    public CustomizationFaultFaultMsg() {
        super();
    }

    public CustomizationFaultFaultMsg(String message) {
        super(message);
    }

    public CustomizationFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CustomizationFaultFaultMsg(String message, com.vmware.vim25.CustomizationFault customizationFaultFault) {
        super(message);
        this.faultInfo = customizationFaultFault;
    }

    public CustomizationFaultFaultMsg(String message, com.vmware.vim25.CustomizationFault customizationFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = customizationFaultFault;
    }

    public com.vmware.vim25.CustomizationFault getFaultInfo() {
        return this.faultInfo;
    }
}
