
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DasConfigFaultFault", targetNamespace = "urn:internalvim25")
public class DasConfigFaultFaultMsg extends Exception {

    private com.vmware.vim25.DasConfigFault faultInfo;

    public DasConfigFaultFaultMsg() {
        super();
    }

    public DasConfigFaultFaultMsg(String message) {
        super(message);
    }

    public DasConfigFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DasConfigFaultFaultMsg(String message, com.vmware.vim25.DasConfigFault dasConfigFaultFault) {
        super(message);
        this.faultInfo = dasConfigFaultFault;
    }

    public DasConfigFaultFaultMsg(String message, com.vmware.vim25.DasConfigFault dasConfigFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = dasConfigFaultFault;
    }

    public com.vmware.vim25.DasConfigFault getFaultInfo() {
        return this.faultInfo;
    }
}
