
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DatacenterMismatchFault", targetNamespace = "urn:internalvim25")
public class DatacenterMismatchFaultMsg extends Exception {

    private com.vmware.vim25.DatacenterMismatch faultInfo;

    public DatacenterMismatchFaultMsg() {
        super();
    }

    public DatacenterMismatchFaultMsg(String message) {
        super(message);
    }

    public DatacenterMismatchFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DatacenterMismatchFaultMsg(String message, com.vmware.vim25.DatacenterMismatch datacenterMismatchFault) {
        super(message);
        this.faultInfo = datacenterMismatchFault;
    }

    public DatacenterMismatchFaultMsg(String message, com.vmware.vim25.DatacenterMismatch datacenterMismatchFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = datacenterMismatchFault;
    }

    public com.vmware.vim25.DatacenterMismatch getFaultInfo() {
        return this.faultInfo;
    }
}
