
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DatastoreNotWritableOnHostFault", targetNamespace = "urn:internalvim25")
public class DatastoreNotWritableOnHostFaultMsg extends Exception {

    private com.vmware.vim25.DatastoreNotWritableOnHost faultInfo;

    public DatastoreNotWritableOnHostFaultMsg() {
        super();
    }

    public DatastoreNotWritableOnHostFaultMsg(String message) {
        super(message);
    }

    public DatastoreNotWritableOnHostFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DatastoreNotWritableOnHostFaultMsg(String message, com.vmware.vim25.DatastoreNotWritableOnHost datastoreNotWritableOnHostFault) {
        super(message);
        this.faultInfo = datastoreNotWritableOnHostFault;
    }

    public DatastoreNotWritableOnHostFaultMsg(String message, com.vmware.vim25.DatastoreNotWritableOnHost datastoreNotWritableOnHostFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = datastoreNotWritableOnHostFault;
    }

    public com.vmware.vim25.DatastoreNotWritableOnHost getFaultInfo() {
        return this.faultInfo;
    }
}
