
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DeviceUnsupportedForVmVersionFault", targetNamespace = "urn:internalvim25")
public class DeviceUnsupportedForVmVersionFaultMsg extends Exception {

    private com.vmware.vim25.DeviceUnsupportedForVmVersion faultInfo;

    public DeviceUnsupportedForVmVersionFaultMsg() {
        super();
    }

    public DeviceUnsupportedForVmVersionFaultMsg(String message) {
        super(message);
    }

    public DeviceUnsupportedForVmVersionFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DeviceUnsupportedForVmVersionFaultMsg(String message, com.vmware.vim25.DeviceUnsupportedForVmVersion deviceUnsupportedForVmVersionFault) {
        super(message);
        this.faultInfo = deviceUnsupportedForVmVersionFault;
    }

    public DeviceUnsupportedForVmVersionFaultMsg(String message, com.vmware.vim25.DeviceUnsupportedForVmVersion deviceUnsupportedForVmVersionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = deviceUnsupportedForVmVersionFault;
    }

    public com.vmware.vim25.DeviceUnsupportedForVmVersion getFaultInfo() {
        return this.faultInfo;
    }
}
