
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DisallowedMigrationDeviceAttachedFault", targetNamespace = "urn:internalvim25")
public class DisallowedMigrationDeviceAttachedFaultMsg extends Exception {

    private com.vmware.vim25.DisallowedMigrationDeviceAttached faultInfo;

    public DisallowedMigrationDeviceAttachedFaultMsg() {
        super();
    }

    public DisallowedMigrationDeviceAttachedFaultMsg(String message) {
        super(message);
    }

    public DisallowedMigrationDeviceAttachedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DisallowedMigrationDeviceAttachedFaultMsg(String message, com.vmware.vim25.DisallowedMigrationDeviceAttached disallowedMigrationDeviceAttachedFault) {
        super(message);
        this.faultInfo = disallowedMigrationDeviceAttachedFault;
    }

    public DisallowedMigrationDeviceAttachedFaultMsg(String message, com.vmware.vim25.DisallowedMigrationDeviceAttached disallowedMigrationDeviceAttachedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = disallowedMigrationDeviceAttachedFault;
    }

    public com.vmware.vim25.DisallowedMigrationDeviceAttached getFaultInfo() {
        return this.faultInfo;
    }
}
