
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DuplicateNameFault", targetNamespace = "urn:internalvim25")
public class DuplicateNameFaultMsg extends Exception {

    private com.vmware.vim25.DuplicateName faultInfo;

    public DuplicateNameFaultMsg() {
        super();
    }

    public DuplicateNameFaultMsg(String message) {
        super(message);
    }

    public DuplicateNameFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DuplicateNameFaultMsg(String message, com.vmware.vim25.DuplicateName duplicateNameFault) {
        super(message);
        this.faultInfo = duplicateNameFault;
    }

    public DuplicateNameFaultMsg(String message, com.vmware.vim25.DuplicateName duplicateNameFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = duplicateNameFault;
    }

    public com.vmware.vim25.DuplicateName getFaultInfo() {
        return this.faultInfo;
    }
}
