
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DvsFaultFault", targetNamespace = "urn:internalvim25")
public class DvsFaultFaultMsg extends Exception {

    private com.vmware.vim25.DvsFault faultInfo;

    public DvsFaultFaultMsg() {
        super();
    }

    public DvsFaultFaultMsg(String message) {
        super(message);
    }

    public DvsFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DvsFaultFaultMsg(String message, com.vmware.vim25.DvsFault dvsFaultFault) {
        super(message);
        this.faultInfo = dvsFaultFault;
    }

    public DvsFaultFaultMsg(String message, com.vmware.vim25.DvsFault dvsFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = dvsFaultFault;
    }

    public com.vmware.vim25.DvsFault getFaultInfo() {
        return this.faultInfo;
    }
}
