
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "DvsNotAuthorizedFault", targetNamespace = "urn:internalvim25")
public class DvsNotAuthorizedFaultMsg extends Exception {

    private com.vmware.vim25.DvsNotAuthorized faultInfo;

    public DvsNotAuthorizedFaultMsg() {
        super();
    }

    public DvsNotAuthorizedFaultMsg(String message) {
        super(message);
    }

    public DvsNotAuthorizedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DvsNotAuthorizedFaultMsg(String message, com.vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault) {
        super(message);
        this.faultInfo = dvsNotAuthorizedFault;
    }

    public DvsNotAuthorizedFaultMsg(String message, com.vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = dvsNotAuthorizedFault;
    }

    public com.vmware.vim25.DvsNotAuthorized getFaultInfo() {
        return this.faultInfo;
    }
}
