
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "EVCConfigFaultFault", targetNamespace = "urn:internalvim25")
public class EVCConfigFaultFaultMsg extends Exception {

    private com.vmware.vim25.EVCConfigFault faultInfo;

    public EVCConfigFaultFaultMsg() {
        super();
    }

    public EVCConfigFaultFaultMsg(String message) {
        super(message);
    }

    public EVCConfigFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EVCConfigFaultFaultMsg(String message, com.vmware.vim25.EVCConfigFault evcConfigFaultFault) {
        super(message);
        this.faultInfo = evcConfigFaultFault;
    }

    public EVCConfigFaultFaultMsg(String message, com.vmware.vim25.EVCConfigFault evcConfigFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = evcConfigFaultFault;
    }

    public com.vmware.vim25.EVCConfigFault getFaultInfo() {
        return this.faultInfo;
    }
}
