
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "FcoeFaultPnicHasNoPortSetFault", targetNamespace = "urn:internalvim25")
public class FcoeFaultPnicHasNoPortSetFaultMsg extends Exception {

    private com.vmware.vim25.FcoeFaultPnicHasNoPortSet faultInfo;

    public FcoeFaultPnicHasNoPortSetFaultMsg() {
        super();
    }

    public FcoeFaultPnicHasNoPortSetFaultMsg(String message) {
        super(message);
    }

    public FcoeFaultPnicHasNoPortSetFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FcoeFaultPnicHasNoPortSetFaultMsg(String message, com.vmware.vim25.FcoeFaultPnicHasNoPortSet fcoeFaultPnicHasNoPortSetFault) {
        super(message);
        this.faultInfo = fcoeFaultPnicHasNoPortSetFault;
    }

    public FcoeFaultPnicHasNoPortSetFaultMsg(String message, com.vmware.vim25.FcoeFaultPnicHasNoPortSet fcoeFaultPnicHasNoPortSetFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fcoeFaultPnicHasNoPortSetFault;
    }

    public com.vmware.vim25.FcoeFaultPnicHasNoPortSet getFaultInfo() {
        return this.faultInfo;
    }
}
