
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "FileAlreadyExistsFault", targetNamespace = "urn:internalvim25")
public class FileAlreadyExistsFaultMsg extends Exception {

    private com.vmware.vim25.FileAlreadyExists faultInfo;

    public FileAlreadyExistsFaultMsg() {
        super();
    }

    public FileAlreadyExistsFaultMsg(String message) {
        super(message);
    }

    public FileAlreadyExistsFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FileAlreadyExistsFaultMsg(String message, com.vmware.vim25.FileAlreadyExists fileAlreadyExistsFault) {
        super(message);
        this.faultInfo = fileAlreadyExistsFault;
    }

    public FileAlreadyExistsFaultMsg(String message, com.vmware.vim25.FileAlreadyExists fileAlreadyExistsFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fileAlreadyExistsFault;
    }

    public com.vmware.vim25.FileAlreadyExists getFaultInfo() {
        return this.faultInfo;
    }
}
