
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "FileNotFoundFault", targetNamespace = "urn:internalvim25")
public class FileNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.FileNotFound faultInfo;

    public FileNotFoundFaultMsg() {
        super();
    }

    public FileNotFoundFaultMsg(String message) {
        super(message);
    }

    public FileNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FileNotFoundFaultMsg(String message, com.vmware.vim25.FileNotFound fileNotFoundFault) {
        super(message);
        this.faultInfo = fileNotFoundFault;
    }

    public FileNotFoundFaultMsg(String message, com.vmware.vim25.FileNotFound fileNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fileNotFoundFault;
    }

    public com.vmware.vim25.FileNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
