
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "FileFaultFault", targetNamespace = "urn:internalvim25")
public class FileFaultFaultMsg extends Exception {

    private com.vmware.vim25.FileFault faultInfo;

    public FileFaultFaultMsg() {
        super();
    }

    public FileFaultFaultMsg(String message) {
        super(message);
    }

    public FileFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FileFaultFaultMsg(String message, com.vmware.vim25.FileFault fileFaultFault) {
        super(message);
        this.faultInfo = fileFaultFault;
    }

    public FileFaultFaultMsg(String message, com.vmware.vim25.FileFault fileFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fileFaultFault;
    }

    public com.vmware.vim25.FileFault getFaultInfo() {
        return this.faultInfo;
    }
}
