
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "FilterInUseFault", targetNamespace = "urn:internalvim25")
public class FilterInUseFaultMsg extends Exception {

    private com.vmware.vim25.FilterInUse faultInfo;

    public FilterInUseFaultMsg() {
        super();
    }

    public FilterInUseFaultMsg(String message) {
        super(message);
    }

    public FilterInUseFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FilterInUseFaultMsg(String message, com.vmware.vim25.FilterInUse filterInUseFault) {
        super(message);
        this.faultInfo = filterInUseFault;
    }

    public FilterInUseFaultMsg(String message, com.vmware.vim25.FilterInUse filterInUseFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = filterInUseFault;
    }

    public com.vmware.vim25.FilterInUse getFaultInfo() {
        return this.faultInfo;
    }
}
