
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "GuestPermissionDeniedFault", targetNamespace = "urn:internalvim25")
public class GuestPermissionDeniedFaultMsg extends Exception {

    private com.vmware.vim25.GuestPermissionDenied faultInfo;

    public GuestPermissionDeniedFaultMsg() {
        super();
    }

    public GuestPermissionDeniedFaultMsg(String message) {
        super(message);
    }

    public GuestPermissionDeniedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GuestPermissionDeniedFaultMsg(String message, com.vmware.vim25.GuestPermissionDenied guestPermissionDeniedFault) {
        super(message);
        this.faultInfo = guestPermissionDeniedFault;
    }

    public GuestPermissionDeniedFaultMsg(String message, com.vmware.vim25.GuestPermissionDenied guestPermissionDeniedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = guestPermissionDeniedFault;
    }

    public com.vmware.vim25.GuestPermissionDenied getFaultInfo() {
        return this.faultInfo;
    }
}
