
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "GuestOperationsFaultFault", targetNamespace = "urn:internalvim25")
public class GuestOperationsFaultFaultMsg extends Exception {

    private com.vmware.vim25.GuestOperationsFault faultInfo;

    public GuestOperationsFaultFaultMsg() {
        super();
    }

    public GuestOperationsFaultFaultMsg(String message) {
        super(message);
    }

    public GuestOperationsFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GuestOperationsFaultFaultMsg(String message, com.vmware.vim25.GuestOperationsFault guestOperationsFaultFault) {
        super(message);
        this.faultInfo = guestOperationsFaultFault;
    }

    public GuestOperationsFaultFaultMsg(String message, com.vmware.vim25.GuestOperationsFault guestOperationsFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = guestOperationsFaultFault;
    }

    public com.vmware.vim25.GuestOperationsFault getFaultInfo() {
        return this.faultInfo;
    }
}
