
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HostConfigFailedFault", targetNamespace = "urn:internalvim25")
public class HostConfigFailedFaultMsg extends Exception {

    private com.vmware.vim25.HostConfigFailed faultInfo;

    public HostConfigFailedFaultMsg() {
        super();
    }

    public HostConfigFailedFaultMsg(String message) {
        super(message);
    }

    public HostConfigFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HostConfigFailedFaultMsg(String message, com.vmware.vim25.HostConfigFailed hostConfigFailedFault) {
        super(message);
        this.faultInfo = hostConfigFailedFault;
    }

    public HostConfigFailedFaultMsg(String message, com.vmware.vim25.HostConfigFailed hostConfigFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hostConfigFailedFault;
    }

    public com.vmware.vim25.HostConfigFailed getFaultInfo() {
        return this.faultInfo;
    }
}
