
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HostSpecificationOperationFailedFault", targetNamespace = "urn:internalvim25")
public class HostSpecificationOperationFailedFaultMsg extends Exception {

    private com.vmware.vim25.HostSpecificationOperationFailed faultInfo;

    public HostSpecificationOperationFailedFaultMsg() {
        super();
    }

    public HostSpecificationOperationFailedFaultMsg(String message) {
        super(message);
    }

    public HostSpecificationOperationFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HostSpecificationOperationFailedFaultMsg(String message, com.vmware.vim25.HostSpecificationOperationFailed hostSpecificationOperationFailedFault) {
        super(message);
        this.faultInfo = hostSpecificationOperationFailedFault;
    }

    public HostSpecificationOperationFailedFaultMsg(String message, com.vmware.vim25.HostSpecificationOperationFailed hostSpecificationOperationFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hostSpecificationOperationFailedFault;
    }

    public com.vmware.vim25.HostSpecificationOperationFailed getFaultInfo() {
        return this.faultInfo;
    }
}
