
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HostPowerOpFailedFault", targetNamespace = "urn:internalvim25")
public class HostPowerOpFailedFaultMsg extends Exception {

    private com.vmware.vim25.HostPowerOpFailed faultInfo;

    public HostPowerOpFailedFaultMsg() {
        super();
    }

    public HostPowerOpFailedFaultMsg(String message) {
        super(message);
    }

    public HostPowerOpFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HostPowerOpFailedFaultMsg(String message, com.vmware.vim25.HostPowerOpFailed hostPowerOpFailedFault) {
        super(message);
        this.faultInfo = hostPowerOpFailedFault;
    }

    public HostPowerOpFailedFaultMsg(String message, com.vmware.vim25.HostPowerOpFailed hostPowerOpFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hostPowerOpFailedFault;
    }

    public com.vmware.vim25.HostPowerOpFailed getFaultInfo() {
        return this.faultInfo;
    }
}
