
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HostConfigFaultFault", targetNamespace = "urn:internalvim25")
public class HostConfigFaultFaultMsg extends Exception {

    private com.vmware.vim25.HostConfigFault faultInfo;

    public HostConfigFaultFaultMsg() {
        super();
    }

    public HostConfigFaultFaultMsg(String message) {
        super(message);
    }

    public HostConfigFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HostConfigFaultFaultMsg(String message, com.vmware.vim25.HostConfigFault hostConfigFaultFault) {
        super(message);
        this.faultInfo = hostConfigFaultFault;
    }

    public HostConfigFaultFaultMsg(String message, com.vmware.vim25.HostConfigFault hostConfigFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hostConfigFaultFault;
    }

    public com.vmware.vim25.HostConfigFault getFaultInfo() {
        return this.faultInfo;
    }
}
