
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HostConnectFaultFault", targetNamespace = "urn:internalvim25")
public class HostConnectFaultFaultMsg extends Exception {

    private com.vmware.vim25.HostConnectFault faultInfo;

    public HostConnectFaultFaultMsg() {
        super();
    }

    public HostConnectFaultFaultMsg(String message) {
        super(message);
    }

    public HostConnectFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HostConnectFaultFaultMsg(String message, com.vmware.vim25.HostConnectFault hostConnectFaultFault) {
        super(message);
        this.faultInfo = hostConnectFaultFault;
    }

    public HostConnectFaultFaultMsg(String message, com.vmware.vim25.HostConnectFault hostConnectFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hostConnectFaultFault;
    }

    public com.vmware.vim25.HostConnectFault getFaultInfo() {
        return this.faultInfo;
    }
}
