
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HostIncompatibleForRecordReplayFault", targetNamespace = "urn:internalvim25")
public class HostIncompatibleForRecordReplayFaultMsg extends Exception {

    private com.vmware.vim25.HostIncompatibleForRecordReplay faultInfo;

    public HostIncompatibleForRecordReplayFaultMsg() {
        super();
    }

    public HostIncompatibleForRecordReplayFaultMsg(String message) {
        super(message);
    }

    public HostIncompatibleForRecordReplayFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HostIncompatibleForRecordReplayFaultMsg(String message, com.vmware.vim25.HostIncompatibleForRecordReplay hostIncompatibleForRecordReplayFault) {
        super(message);
        this.faultInfo = hostIncompatibleForRecordReplayFault;
    }

    public HostIncompatibleForRecordReplayFaultMsg(String message, com.vmware.vim25.HostIncompatibleForRecordReplay hostIncompatibleForRecordReplayFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hostIncompatibleForRecordReplayFault;
    }

    public com.vmware.vim25.HostIncompatibleForRecordReplay getFaultInfo() {
        return this.faultInfo;
    }
}
