
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "HttpFaultFault", targetNamespace = "urn:internalvim25")
public class HttpFaultFaultMsg extends Exception {

    private com.vmware.vim25.HttpFault faultInfo;

    public HttpFaultFaultMsg() {
        super();
    }

    public HttpFaultFaultMsg(String message) {
        super(message);
    }

    public HttpFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HttpFaultFaultMsg(String message, com.vmware.vim25.HttpFault httpFaultFault) {
        super(message);
        this.faultInfo = httpFaultFault;
    }

    public HttpFaultFaultMsg(String message, com.vmware.vim25.HttpFault httpFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = httpFaultFault;
    }

    public com.vmware.vim25.HttpFault getFaultInfo() {
        return this.faultInfo;
    }
}
