
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InaccessibleVFlashSourceFault", targetNamespace = "urn:internalvim25")
public class InaccessibleVFlashSourceFaultMsg extends Exception {

    private com.vmware.vim25.InaccessibleVFlashSource faultInfo;

    public InaccessibleVFlashSourceFaultMsg() {
        super();
    }

    public InaccessibleVFlashSourceFaultMsg(String message) {
        super(message);
    }

    public InaccessibleVFlashSourceFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InaccessibleVFlashSourceFaultMsg(String message, com.vmware.vim25.InaccessibleVFlashSource inaccessibleVFlashSourceFault) {
        super(message);
        this.faultInfo = inaccessibleVFlashSourceFault;
    }

    public InaccessibleVFlashSourceFaultMsg(String message, com.vmware.vim25.InaccessibleVFlashSource inaccessibleVFlashSourceFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = inaccessibleVFlashSourceFault;
    }

    public com.vmware.vim25.InaccessibleVFlashSource getFaultInfo() {
        return this.faultInfo;
    }
}
