
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InaccessibleDatastoreFault", targetNamespace = "urn:internalvim25")
public class InaccessibleDatastoreFaultMsg extends Exception {

    private com.vmware.vim25.InaccessibleDatastore faultInfo;

    public InaccessibleDatastoreFaultMsg() {
        super();
    }

    public InaccessibleDatastoreFaultMsg(String message) {
        super(message);
    }

    public InaccessibleDatastoreFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InaccessibleDatastoreFaultMsg(String message, com.vmware.vim25.InaccessibleDatastore inaccessibleDatastoreFault) {
        super(message);
        this.faultInfo = inaccessibleDatastoreFault;
    }

    public InaccessibleDatastoreFaultMsg(String message, com.vmware.vim25.InaccessibleDatastore inaccessibleDatastoreFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = inaccessibleDatastoreFault;
    }

    public com.vmware.vim25.InaccessibleDatastore getFaultInfo() {
        return this.faultInfo;
    }
}
