
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InsufficientResourcesFaultFault", targetNamespace = "urn:internalvim25")
public class InsufficientResourcesFaultFaultMsg extends Exception {

    private com.vmware.vim25.InsufficientResourcesFault faultInfo;

    public InsufficientResourcesFaultFaultMsg() {
        super();
    }

    public InsufficientResourcesFaultFaultMsg(String message) {
        super(message);
    }

    public InsufficientResourcesFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InsufficientResourcesFaultFaultMsg(String message, com.vmware.vim25.InsufficientResourcesFault insufficientResourcesFaultFault) {
        super(message);
        this.faultInfo = insufficientResourcesFaultFault;
    }

    public InsufficientResourcesFaultFaultMsg(String message, com.vmware.vim25.InsufficientResourcesFault insufficientResourcesFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = insufficientResourcesFaultFault;
    }

    public com.vmware.vim25.InsufficientResourcesFault getFaultInfo() {
        return this.faultInfo;
    }
}
