
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidCollectorVersionFault", targetNamespace = "urn:internalvim25")
public class InvalidCollectorVersionFaultMsg extends Exception {

    private com.vmware.vim25.InvalidCollectorVersion faultInfo;

    public InvalidCollectorVersionFaultMsg() {
        super();
    }

    public InvalidCollectorVersionFaultMsg(String message) {
        super(message);
    }

    public InvalidCollectorVersionFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidCollectorVersionFaultMsg(String message, com.vmware.vim25.InvalidCollectorVersion invalidCollectorVersionFault) {
        super(message);
        this.faultInfo = invalidCollectorVersionFault;
    }

    public InvalidCollectorVersionFaultMsg(String message, com.vmware.vim25.InvalidCollectorVersion invalidCollectorVersionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidCollectorVersionFault;
    }

    public com.vmware.vim25.InvalidCollectorVersion getFaultInfo() {
        return this.faultInfo;
    }
}
