
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidBundleFault", targetNamespace = "urn:internalvim25")
public class InvalidBundleFaultMsg extends Exception {

    private com.vmware.vim25.InvalidBundle faultInfo;

    public InvalidBundleFaultMsg() {
        super();
    }

    public InvalidBundleFaultMsg(String message) {
        super(message);
    }

    public InvalidBundleFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidBundleFaultMsg(String message, com.vmware.vim25.InvalidBundle invalidBundleFault) {
        super(message);
        this.faultInfo = invalidBundleFault;
    }

    public InvalidBundleFaultMsg(String message, com.vmware.vim25.InvalidBundle invalidBundleFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidBundleFault;
    }

    public com.vmware.vim25.InvalidBundle getFaultInfo() {
        return this.faultInfo;
    }
}
