
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidIpmiLoginInfoFault", targetNamespace = "urn:internalvim25")
public class InvalidIpmiLoginInfoFaultMsg extends Exception {

    private com.vmware.vim25.InvalidIpmiLoginInfo faultInfo;

    public InvalidIpmiLoginInfoFaultMsg() {
        super();
    }

    public InvalidIpmiLoginInfoFaultMsg(String message) {
        super(message);
    }

    public InvalidIpmiLoginInfoFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidIpmiLoginInfoFaultMsg(String message, com.vmware.vim25.InvalidIpmiLoginInfo invalidIpmiLoginInfoFault) {
        super(message);
        this.faultInfo = invalidIpmiLoginInfoFault;
    }

    public InvalidIpmiLoginInfoFaultMsg(String message, com.vmware.vim25.InvalidIpmiLoginInfo invalidIpmiLoginInfoFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidIpmiLoginInfoFault;
    }

    public com.vmware.vim25.InvalidIpmiLoginInfo getFaultInfo() {
        return this.faultInfo;
    }
}
