
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidArgumentFault", targetNamespace = "urn:internalvim25")
public class InvalidArgumentFaultMsg extends Exception {

    private com.vmware.vim25.InvalidArgument faultInfo;

    public InvalidArgumentFaultMsg() {
        super();
    }

    public InvalidArgumentFaultMsg(String message) {
        super(message);
    }

    public InvalidArgumentFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentFaultMsg(String message, com.vmware.vim25.InvalidArgument invalidArgumentFault) {
        super(message);
        this.faultInfo = invalidArgumentFault;
    }

    public InvalidArgumentFaultMsg(String message, com.vmware.vim25.InvalidArgument invalidArgumentFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidArgumentFault;
    }

    public com.vmware.vim25.InvalidArgument getFaultInfo() {
        return this.faultInfo;
    }
}
