
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidControllerFault", targetNamespace = "urn:internalvim25")
public class InvalidControllerFaultMsg extends Exception {

    private com.vmware.vim25.InvalidController faultInfo;

    public InvalidControllerFaultMsg() {
        super();
    }

    public InvalidControllerFaultMsg(String message) {
        super(message);
    }

    public InvalidControllerFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidControllerFaultMsg(String message, com.vmware.vim25.InvalidController invalidControllerFault) {
        super(message);
        this.faultInfo = invalidControllerFault;
    }

    public InvalidControllerFaultMsg(String message, com.vmware.vim25.InvalidController invalidControllerFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidControllerFault;
    }

    public com.vmware.vim25.InvalidController getFaultInfo() {
        return this.faultInfo;
    }
}
