
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidPrivilegeFault", targetNamespace = "urn:internalvim25")
public class InvalidPrivilegeFaultMsg extends Exception {

    private com.vmware.vim25.InvalidPrivilege faultInfo;

    public InvalidPrivilegeFaultMsg() {
        super();
    }

    public InvalidPrivilegeFaultMsg(String message) {
        super(message);
    }

    public InvalidPrivilegeFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidPrivilegeFaultMsg(String message, com.vmware.vim25.InvalidPrivilege invalidPrivilegeFault) {
        super(message);
        this.faultInfo = invalidPrivilegeFault;
    }

    public InvalidPrivilegeFaultMsg(String message, com.vmware.vim25.InvalidPrivilege invalidPrivilegeFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidPrivilegeFault;
    }

    public com.vmware.vim25.InvalidPrivilege getFaultInfo() {
        return this.faultInfo;
    }
}
