
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidEventFault", targetNamespace = "urn:internalvim25")
public class InvalidEventFaultMsg extends Exception {

    private com.vmware.vim25.InvalidEvent faultInfo;

    public InvalidEventFaultMsg() {
        super();
    }

    public InvalidEventFaultMsg(String message) {
        super(message);
    }

    public InvalidEventFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidEventFaultMsg(String message, com.vmware.vim25.InvalidEvent invalidEventFault) {
        super(message);
        this.faultInfo = invalidEventFault;
    }

    public InvalidEventFaultMsg(String message, com.vmware.vim25.InvalidEvent invalidEventFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidEventFault;
    }

    public com.vmware.vim25.InvalidEvent getFaultInfo() {
        return this.faultInfo;
    }
}
