
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidFolderFault", targetNamespace = "urn:internalvim25")
public class InvalidFolderFaultMsg extends Exception {

    private com.vmware.vim25.InvalidFolder faultInfo;

    public InvalidFolderFaultMsg() {
        super();
    }

    public InvalidFolderFaultMsg(String message) {
        super(message);
    }

    public InvalidFolderFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidFolderFaultMsg(String message, com.vmware.vim25.InvalidFolder invalidFolderFault) {
        super(message);
        this.faultInfo = invalidFolderFault;
    }

    public InvalidFolderFaultMsg(String message, com.vmware.vim25.InvalidFolder invalidFolderFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidFolderFault;
    }

    public com.vmware.vim25.InvalidFolder getFaultInfo() {
        return this.faultInfo;
    }
}
