
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidLoginFault", targetNamespace = "urn:internalvim25")
public class InvalidLoginFaultMsg extends Exception {

    private com.vmware.vim25.InvalidLogin faultInfo;

    public InvalidLoginFaultMsg() {
        super();
    }

    public InvalidLoginFaultMsg(String message) {
        super(message);
    }

    public InvalidLoginFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidLoginFaultMsg(String message, com.vmware.vim25.InvalidLogin invalidLoginFault) {
        super(message);
        this.faultInfo = invalidLoginFault;
    }

    public InvalidLoginFaultMsg(String message, com.vmware.vim25.InvalidLogin invalidLoginFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidLoginFault;
    }

    public com.vmware.vim25.InvalidLogin getFaultInfo() {
        return this.faultInfo;
    }
}
