
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidPowerStateFault", targetNamespace = "urn:internalvim25")
public class InvalidPowerStateFaultMsg extends Exception {

    private com.vmware.vim25.InvalidPowerState faultInfo;

    public InvalidPowerStateFaultMsg() {
        super();
    }

    public InvalidPowerStateFaultMsg(String message) {
        super(message);
    }

    public InvalidPowerStateFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidPowerStateFaultMsg(String message, com.vmware.vim25.InvalidPowerState invalidPowerStateFault) {
        super(message);
        this.faultInfo = invalidPowerStateFault;
    }

    public InvalidPowerStateFaultMsg(String message, com.vmware.vim25.InvalidPowerState invalidPowerStateFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidPowerStateFault;
    }

    public com.vmware.vim25.InvalidPowerState getFaultInfo() {
        return this.faultInfo;
    }
}
