
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidRequestFault", targetNamespace = "urn:internalvim25")
public class InvalidRequestFaultMsg extends Exception {

    private com.vmware.vim25.InvalidRequest faultInfo;

    public InvalidRequestFaultMsg() {
        super();
    }

    public InvalidRequestFaultMsg(String message) {
        super(message);
    }

    public InvalidRequestFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidRequestFaultMsg(String message, com.vmware.vim25.InvalidRequest invalidRequestFault) {
        super(message);
        this.faultInfo = invalidRequestFault;
    }

    public InvalidRequestFaultMsg(String message, com.vmware.vim25.InvalidRequest invalidRequestFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidRequestFault;
    }

    public com.vmware.vim25.InvalidRequest getFaultInfo() {
        return this.faultInfo;
    }
}
