
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidLocaleFault", targetNamespace = "urn:internalvim25")
public class InvalidLocaleFaultMsg extends Exception {

    private com.vmware.vim25.InvalidLocale faultInfo;

    public InvalidLocaleFaultMsg() {
        super();
    }

    public InvalidLocaleFaultMsg(String message) {
        super(message);
    }

    public InvalidLocaleFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidLocaleFaultMsg(String message, com.vmware.vim25.InvalidLocale invalidLocaleFault) {
        super(message);
        this.faultInfo = invalidLocaleFault;
    }

    public InvalidLocaleFaultMsg(String message, com.vmware.vim25.InvalidLocale invalidLocaleFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidLocaleFault;
    }

    public com.vmware.vim25.InvalidLocale getFaultInfo() {
        return this.faultInfo;
    }
}
