
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidGuestLoginFault", targetNamespace = "urn:internalvim25")
public class InvalidGuestLoginFaultMsg extends Exception {

    private com.vmware.vim25.InvalidGuestLogin faultInfo;

    public InvalidGuestLoginFaultMsg() {
        super();
    }

    public InvalidGuestLoginFaultMsg(String message) {
        super(message);
    }

    public InvalidGuestLoginFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidGuestLoginFaultMsg(String message, com.vmware.vim25.InvalidGuestLogin invalidGuestLoginFault) {
        super(message);
        this.faultInfo = invalidGuestLoginFault;
    }

    public InvalidGuestLoginFaultMsg(String message, com.vmware.vim25.InvalidGuestLogin invalidGuestLoginFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidGuestLoginFault;
    }

    public com.vmware.vim25.InvalidGuestLogin getFaultInfo() {
        return this.faultInfo;
    }
}
