
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidIpmiMacAddressFault", targetNamespace = "urn:internalvim25")
public class InvalidIpmiMacAddressFaultMsg extends Exception {

    private com.vmware.vim25.InvalidIpmiMacAddress faultInfo;

    public InvalidIpmiMacAddressFaultMsg() {
        super();
    }

    public InvalidIpmiMacAddressFaultMsg(String message) {
        super(message);
    }

    public InvalidIpmiMacAddressFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidIpmiMacAddressFaultMsg(String message, com.vmware.vim25.InvalidIpmiMacAddress invalidIpmiMacAddressFault) {
        super(message);
        this.faultInfo = invalidIpmiMacAddressFault;
    }

    public InvalidIpmiMacAddressFaultMsg(String message, com.vmware.vim25.InvalidIpmiMacAddress invalidIpmiMacAddressFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidIpmiMacAddressFault;
    }

    public com.vmware.vim25.InvalidIpmiMacAddress getFaultInfo() {
        return this.faultInfo;
    }
}
