
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidLicenseFault", targetNamespace = "urn:internalvim25")
public class InvalidLicenseFaultMsg extends Exception {

    private com.vmware.vim25.InvalidLicense faultInfo;

    public InvalidLicenseFaultMsg() {
        super();
    }

    public InvalidLicenseFaultMsg(String message) {
        super(message);
    }

    public InvalidLicenseFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidLicenseFaultMsg(String message, com.vmware.vim25.InvalidLicense invalidLicenseFault) {
        super(message);
        this.faultInfo = invalidLicenseFault;
    }

    public InvalidLicenseFaultMsg(String message, com.vmware.vim25.InvalidLicense invalidLicenseFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidLicenseFault;
    }

    public com.vmware.vim25.InvalidLicense getFaultInfo() {
        return this.faultInfo;
    }
}
