
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidPropertyFault", targetNamespace = "urn:internalvim25")
public class InvalidPropertyFaultMsg extends Exception {

    private com.vmware.vim25.InvalidProperty faultInfo;

    public InvalidPropertyFaultMsg() {
        super();
    }

    public InvalidPropertyFaultMsg(String message) {
        super(message);
    }

    public InvalidPropertyFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidPropertyFaultMsg(String message, com.vmware.vim25.InvalidProperty invalidPropertyFault) {
        super(message);
        this.faultInfo = invalidPropertyFault;
    }

    public InvalidPropertyFaultMsg(String message, com.vmware.vim25.InvalidProperty invalidPropertyFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidPropertyFault;
    }

    public com.vmware.vim25.InvalidProperty getFaultInfo() {
        return this.faultInfo;
    }
}
