
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidNameFault", targetNamespace = "urn:internalvim25")
public class InvalidNameFaultMsg extends Exception {

    private com.vmware.vim25.InvalidName faultInfo;

    public InvalidNameFaultMsg() {
        super();
    }

    public InvalidNameFaultMsg(String message) {
        super(message);
    }

    public InvalidNameFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidNameFaultMsg(String message, com.vmware.vim25.InvalidName invalidNameFault) {
        super(message);
        this.faultInfo = invalidNameFault;
    }

    public InvalidNameFaultMsg(String message, com.vmware.vim25.InvalidName invalidNameFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidNameFault;
    }

    public com.vmware.vim25.InvalidName getFaultInfo() {
        return this.faultInfo;
    }
}
