
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidDatastorePathFault", targetNamespace = "urn:internalvim25")
public class InvalidDatastorePathFaultMsg extends Exception {

    private com.vmware.vim25.InvalidDatastorePath faultInfo;

    public InvalidDatastorePathFaultMsg() {
        super();
    }

    public InvalidDatastorePathFaultMsg(String message) {
        super(message);
    }

    public InvalidDatastorePathFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidDatastorePathFaultMsg(String message, com.vmware.vim25.InvalidDatastorePath invalidDatastorePathFault) {
        super(message);
        this.faultInfo = invalidDatastorePathFault;
    }

    public InvalidDatastorePathFaultMsg(String message, com.vmware.vim25.InvalidDatastorePath invalidDatastorePathFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidDatastorePathFault;
    }

    public com.vmware.vim25.InvalidDatastorePath getFaultInfo() {
        return this.faultInfo;
    }
}
