
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidDatastoreFault", targetNamespace = "urn:internalvim25")
public class InvalidDatastoreFaultMsg extends Exception {

    private com.vmware.vim25.InvalidDatastore faultInfo;

    public InvalidDatastoreFaultMsg() {
        super();
    }

    public InvalidDatastoreFaultMsg(String message) {
        super(message);
    }

    public InvalidDatastoreFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidDatastoreFaultMsg(String message, com.vmware.vim25.InvalidDatastore invalidDatastoreFault) {
        super(message);
        this.faultInfo = invalidDatastoreFault;
    }

    public InvalidDatastoreFaultMsg(String message, com.vmware.vim25.InvalidDatastore invalidDatastoreFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidDatastoreFault;
    }

    public com.vmware.vim25.InvalidDatastore getFaultInfo() {
        return this.faultInfo;
    }
}
