
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidStateFault", targetNamespace = "urn:internalvim25")
public class InvalidStateFaultMsg extends Exception {

    private com.vmware.vim25.InvalidState faultInfo;

    public InvalidStateFaultMsg() {
        super();
    }

    public InvalidStateFaultMsg(String message) {
        super(message);
    }

    public InvalidStateFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidStateFaultMsg(String message, com.vmware.vim25.InvalidState invalidStateFault) {
        super(message);
        this.faultInfo = invalidStateFault;
    }

    public InvalidStateFaultMsg(String message, com.vmware.vim25.InvalidState invalidStateFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidStateFault;
    }

    public com.vmware.vim25.InvalidState getFaultInfo() {
        return this.faultInfo;
    }
}
