
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidDiskFormatFault", targetNamespace = "urn:internalvim25")
public class InvalidDiskFormatFaultMsg extends Exception {

    private com.vmware.vim25.InvalidDiskFormat faultInfo;

    public InvalidDiskFormatFaultMsg() {
        super();
    }

    public InvalidDiskFormatFaultMsg(String message) {
        super(message);
    }

    public InvalidDiskFormatFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidDiskFormatFaultMsg(String message, com.vmware.vim25.InvalidDiskFormat invalidDiskFormatFault) {
        super(message);
        this.faultInfo = invalidDiskFormatFault;
    }

    public InvalidDiskFormatFaultMsg(String message, com.vmware.vim25.InvalidDiskFormat invalidDiskFormatFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidDiskFormatFault;
    }

    public com.vmware.vim25.InvalidDiskFormat getFaultInfo() {
        return this.faultInfo;
    }
}
