
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidTypeFault", targetNamespace = "urn:internalvim25")
public class InvalidTypeFaultMsg extends Exception {

    private com.vmware.vim25.InvalidType faultInfo;

    public InvalidTypeFaultMsg() {
        super();
    }

    public InvalidTypeFaultMsg(String message) {
        super(message);
    }

    public InvalidTypeFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidTypeFaultMsg(String message, com.vmware.vim25.InvalidType invalidTypeFault) {
        super(message);
        this.faultInfo = invalidTypeFault;
    }

    public InvalidTypeFaultMsg(String message, com.vmware.vim25.InvalidType invalidTypeFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidTypeFault;
    }

    public com.vmware.vim25.InvalidType getFaultInfo() {
        return this.faultInfo;
    }
}
