
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidHostStateFault", targetNamespace = "urn:internalvim25")
public class InvalidHostStateFaultMsg extends Exception {

    private com.vmware.vim25.InvalidHostState faultInfo;

    public InvalidHostStateFaultMsg() {
        super();
    }

    public InvalidHostStateFaultMsg(String message) {
        super(message);
    }

    public InvalidHostStateFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidHostStateFaultMsg(String message, com.vmware.vim25.InvalidHostState invalidHostStateFault) {
        super(message);
        this.faultInfo = invalidHostStateFault;
    }

    public InvalidHostStateFaultMsg(String message, com.vmware.vim25.InvalidHostState invalidHostStateFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidHostStateFault;
    }

    public com.vmware.vim25.InvalidHostState getFaultInfo() {
        return this.faultInfo;
    }
}
