
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IORMNotSupportedHostOnDatastoreFault", targetNamespace = "urn:internalvim25")
public class IORMNotSupportedHostOnDatastoreFaultMsg extends Exception {

    private com.vmware.vim25.IORMNotSupportedHostOnDatastore faultInfo;

    public IORMNotSupportedHostOnDatastoreFaultMsg() {
        super();
    }

    public IORMNotSupportedHostOnDatastoreFaultMsg(String message) {
        super(message);
    }

    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, com.vmware.vim25.IORMNotSupportedHostOnDatastore iormNotSupportedHostOnDatastoreFault) {
        super(message);
        this.faultInfo = iormNotSupportedHostOnDatastoreFault;
    }

    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, com.vmware.vim25.IORMNotSupportedHostOnDatastore iormNotSupportedHostOnDatastoreFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iormNotSupportedHostOnDatastoreFault;
    }

    public com.vmware.vim25.IORMNotSupportedHostOnDatastore getFaultInfo() {
        return this.faultInfo;
    }
}
