
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicNotBoundFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicNotBoundFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicNotBound faultInfo;

    public IscsiFaultVnicNotBoundFaultMsg() {
        super();
    }

    public IscsiFaultVnicNotBoundFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicNotBoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicNotBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotBound iscsiFaultVnicNotBoundFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicNotBoundFault;
    }

    public IscsiFaultVnicNotBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotBound iscsiFaultVnicNotBoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicNotBoundFault;
    }

    public com.vmware.vim25.IscsiFaultVnicNotBound getFaultInfo() {
        return this.faultInfo;
    }
}
