
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicHasWrongUplinkFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicHasWrongUplinkFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicHasWrongUplink faultInfo;

    public IscsiFaultVnicHasWrongUplinkFaultMsg() {
        super();
    }

    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasWrongUplink iscsiFaultVnicHasWrongUplinkFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicHasWrongUplinkFault;
    }

    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasWrongUplink iscsiFaultVnicHasWrongUplinkFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicHasWrongUplinkFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasWrongUplink getFaultInfo() {
        return this.faultInfo;
    }
}
