
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicHasActivePathsFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicHasActivePathsFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicHasActivePaths faultInfo;

    public IscsiFaultVnicHasActivePathsFaultMsg() {
        super();
    }

    public IscsiFaultVnicHasActivePathsFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicHasActivePathsFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasActivePathsFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasActivePaths iscsiFaultVnicHasActivePathsFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicHasActivePathsFault;
    }

    public IscsiFaultVnicHasActivePathsFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasActivePaths iscsiFaultVnicHasActivePathsFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicHasActivePathsFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasActivePaths getFaultInfo() {
        return this.faultInfo;
    }
}
