
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicHasMultipleUplinksFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicHasMultipleUplinksFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks faultInfo;

    public IscsiFaultVnicHasMultipleUplinksFaultMsg() {
        super();
    }

    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks iscsiFaultVnicHasMultipleUplinksFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicHasMultipleUplinksFault;
    }

    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks iscsiFaultVnicHasMultipleUplinksFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicHasMultipleUplinksFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks getFaultInfo() {
        return this.faultInfo;
    }
}
