
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFault faultInfo;

    public IscsiFaultFaultMsg() {
        super();
    }

    public IscsiFaultFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultFaultMsg(String message, com.vmware.vim25.IscsiFault iscsiFaultFault) {
        super(message);
        this.faultInfo = iscsiFaultFault;
    }

    public IscsiFaultFaultMsg(String message, com.vmware.vim25.IscsiFault iscsiFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultFault;
    }

    public com.vmware.vim25.IscsiFault getFaultInfo() {
        return this.faultInfo;
    }
}
