
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicHasNoUplinksFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicHasNoUplinksFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicHasNoUplinks faultInfo;

    public IscsiFaultVnicHasNoUplinksFaultMsg() {
        super();
    }

    public IscsiFaultVnicHasNoUplinksFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicHasNoUplinksFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasNoUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasNoUplinks iscsiFaultVnicHasNoUplinksFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicHasNoUplinksFault;
    }

    public IscsiFaultVnicHasNoUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasNoUplinks iscsiFaultVnicHasNoUplinksFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicHasNoUplinksFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasNoUplinks getFaultInfo() {
        return this.faultInfo;
    }
}
