
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicNotFoundFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicNotFound faultInfo;

    public IscsiFaultVnicNotFoundFaultMsg() {
        super();
    }

    public IscsiFaultVnicNotFoundFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicNotFoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotFound iscsiFaultVnicNotFoundFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicNotFoundFault;
    }

    public IscsiFaultVnicNotFoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotFound iscsiFaultVnicNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicNotFoundFault;
    }

    public com.vmware.vim25.IscsiFaultVnicNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
