
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicAlreadyBoundFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicAlreadyBoundFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicAlreadyBound faultInfo;

    public IscsiFaultVnicAlreadyBoundFaultMsg() {
        super();
    }

    public IscsiFaultVnicAlreadyBoundFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicAlreadyBoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicAlreadyBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicAlreadyBound iscsiFaultVnicAlreadyBoundFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicAlreadyBoundFault;
    }

    public IscsiFaultVnicAlreadyBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicAlreadyBound iscsiFaultVnicAlreadyBoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicAlreadyBoundFault;
    }

    public com.vmware.vim25.IscsiFaultVnicAlreadyBound getFaultInfo() {
        return this.faultInfo;
    }
}
