
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultVnicIsLastPathFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultVnicIsLastPathFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultVnicIsLastPath faultInfo;

    public IscsiFaultVnicIsLastPathFaultMsg() {
        super();
    }

    public IscsiFaultVnicIsLastPathFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultVnicIsLastPathFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicIsLastPathFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicIsLastPath iscsiFaultVnicIsLastPathFault) {
        super(message);
        this.faultInfo = iscsiFaultVnicIsLastPathFault;
    }

    public IscsiFaultVnicIsLastPathFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicIsLastPath iscsiFaultVnicIsLastPathFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultVnicIsLastPathFault;
    }

    public com.vmware.vim25.IscsiFaultVnicIsLastPath getFaultInfo() {
        return this.faultInfo;
    }
}
