
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "IscsiFaultInvalidVnicFault", targetNamespace = "urn:internalvim25")
public class IscsiFaultInvalidVnicFaultMsg extends Exception {

    private com.vmware.vim25.IscsiFaultInvalidVnic faultInfo;

    public IscsiFaultInvalidVnicFaultMsg() {
        super();
    }

    public IscsiFaultInvalidVnicFaultMsg(String message) {
        super(message);
    }

    public IscsiFaultInvalidVnicFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultInvalidVnicFaultMsg(String message, com.vmware.vim25.IscsiFaultInvalidVnic iscsiFaultInvalidVnicFault) {
        super(message);
        this.faultInfo = iscsiFaultInvalidVnicFault;
    }

    public IscsiFaultInvalidVnicFaultMsg(String message, com.vmware.vim25.IscsiFaultInvalidVnic iscsiFaultInvalidVnicFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = iscsiFaultInvalidVnicFault;
    }

    public com.vmware.vim25.IscsiFaultInvalidVnic getFaultInfo() {
        return this.faultInfo;
    }
}
