
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "KeyNotFoundFault", targetNamespace = "urn:internalvim25")
public class KeyNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.KeyNotFound faultInfo;

    public KeyNotFoundFaultMsg() {
        super();
    }

    public KeyNotFoundFaultMsg(String message) {
        super(message);
    }

    public KeyNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public KeyNotFoundFaultMsg(String message, com.vmware.vim25.KeyNotFound keyNotFoundFault) {
        super(message);
        this.faultInfo = keyNotFoundFault;
    }

    public KeyNotFoundFaultMsg(String message, com.vmware.vim25.KeyNotFound keyNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = keyNotFoundFault;
    }

    public com.vmware.vim25.KeyNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
