
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "LicenseEntityNotFoundFault", targetNamespace = "urn:internalvim25")
public class LicenseEntityNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.LicenseEntityNotFound faultInfo;

    public LicenseEntityNotFoundFaultMsg() {
        super();
    }

    public LicenseEntityNotFoundFaultMsg(String message) {
        super(message);
    }

    public LicenseEntityNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LicenseEntityNotFoundFaultMsg(String message, com.vmware.vim25.LicenseEntityNotFound licenseEntityNotFoundFault) {
        super(message);
        this.faultInfo = licenseEntityNotFoundFault;
    }

    public LicenseEntityNotFoundFaultMsg(String message, com.vmware.vim25.LicenseEntityNotFound licenseEntityNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = licenseEntityNotFoundFault;
    }

    public com.vmware.vim25.LicenseEntityNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
