
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "LicenseServerUnavailableFault", targetNamespace = "urn:internalvim25")
public class LicenseServerUnavailableFaultMsg extends Exception {

    private com.vmware.vim25.LicenseServerUnavailable faultInfo;

    public LicenseServerUnavailableFaultMsg() {
        super();
    }

    public LicenseServerUnavailableFaultMsg(String message) {
        super(message);
    }

    public LicenseServerUnavailableFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LicenseServerUnavailableFaultMsg(String message, com.vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault) {
        super(message);
        this.faultInfo = licenseServerUnavailableFault;
    }

    public LicenseServerUnavailableFaultMsg(String message, com.vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = licenseServerUnavailableFault;
    }

    public com.vmware.vim25.LicenseServerUnavailable getFaultInfo() {
        return this.faultInfo;
    }
}
