
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "LimitExceededFault", targetNamespace = "urn:internalvim25")
public class LimitExceededFaultMsg extends Exception {

    private com.vmware.vim25.LimitExceeded faultInfo;

    public LimitExceededFaultMsg() {
        super();
    }

    public LimitExceededFaultMsg(String message) {
        super(message);
    }

    public LimitExceededFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LimitExceededFaultMsg(String message, com.vmware.vim25.LimitExceeded limitExceededFault) {
        super(message);
        this.faultInfo = limitExceededFault;
    }

    public LimitExceededFaultMsg(String message, com.vmware.vim25.LimitExceeded limitExceededFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = limitExceededFault;
    }

    public com.vmware.vim25.LimitExceeded getFaultInfo() {
        return this.faultInfo;
    }
}
