
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "LogBundlingFailedFault", targetNamespace = "urn:internalvim25")
public class LogBundlingFailedFaultMsg extends Exception {

    private com.vmware.vim25.LogBundlingFailed faultInfo;

    public LogBundlingFailedFaultMsg() {
        super();
    }

    public LogBundlingFailedFaultMsg(String message) {
        super(message);
    }

    public LogBundlingFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LogBundlingFailedFaultMsg(String message, com.vmware.vim25.LogBundlingFailed logBundlingFailedFault) {
        super(message);
        this.faultInfo = logBundlingFailedFault;
    }

    public LogBundlingFailedFaultMsg(String message, com.vmware.vim25.LogBundlingFailed logBundlingFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = logBundlingFailedFault;
    }

    public com.vmware.vim25.LogBundlingFailed getFaultInfo() {
        return this.faultInfo;
    }
}
