
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ManagedObjectNotFoundFault", targetNamespace = "urn:internalvim25")
public class ManagedObjectNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.ManagedObjectNotFound faultInfo;

    public ManagedObjectNotFoundFaultMsg() {
        super();
    }

    public ManagedObjectNotFoundFaultMsg(String message) {
        super(message);
    }

    public ManagedObjectNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ManagedObjectNotFoundFaultMsg(String message, com.vmware.vim25.ManagedObjectNotFound managedObjectNotFoundFault) {
        super(message);
        this.faultInfo = managedObjectNotFoundFault;
    }

    public ManagedObjectNotFoundFaultMsg(String message, com.vmware.vim25.ManagedObjectNotFound managedObjectNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = managedObjectNotFoundFault;
    }

    public com.vmware.vim25.ManagedObjectNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
