
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "MigrationFaultFault", targetNamespace = "urn:internalvim25")
public class MigrationFaultFaultMsg extends Exception {

    private com.vmware.vim25.MigrationFault faultInfo;

    public MigrationFaultFaultMsg() {
        super();
    }

    public MigrationFaultFaultMsg(String message) {
        super(message);
    }

    public MigrationFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MigrationFaultFaultMsg(String message, com.vmware.vim25.MigrationFault migrationFaultFault) {
        super(message);
        this.faultInfo = migrationFaultFault;
    }

    public MigrationFaultFaultMsg(String message, com.vmware.vim25.MigrationFault migrationFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = migrationFaultFault;
    }

    public com.vmware.vim25.MigrationFault getFaultInfo() {
        return this.faultInfo;
    }
}
