
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "MismatchedBundleFault", targetNamespace = "urn:internalvim25")
public class MismatchedBundleFaultMsg extends Exception {

    private com.vmware.vim25.MismatchedBundle faultInfo;

    public MismatchedBundleFaultMsg() {
        super();
    }

    public MismatchedBundleFaultMsg(String message) {
        super(message);
    }

    public MismatchedBundleFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MismatchedBundleFaultMsg(String message, com.vmware.vim25.MismatchedBundle mismatchedBundleFault) {
        super(message);
        this.faultInfo = mismatchedBundleFault;
    }

    public MismatchedBundleFaultMsg(String message, com.vmware.vim25.MismatchedBundle mismatchedBundleFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = mismatchedBundleFault;
    }

    public com.vmware.vim25.MismatchedBundle getFaultInfo() {
        return this.faultInfo;
    }
}
