
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "MissingControllerFault", targetNamespace = "urn:internalvim25")
public class MissingControllerFaultMsg extends Exception {

    private com.vmware.vim25.MissingController faultInfo;

    public MissingControllerFaultMsg() {
        super();
    }

    public MissingControllerFaultMsg(String message) {
        super(message);
    }

    public MissingControllerFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MissingControllerFaultMsg(String message, com.vmware.vim25.MissingController missingControllerFault) {
        super(message);
        this.faultInfo = missingControllerFault;
    }

    public MissingControllerFaultMsg(String message, com.vmware.vim25.MissingController missingControllerFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = missingControllerFault;
    }

    public com.vmware.vim25.MissingController getFaultInfo() {
        return this.faultInfo;
    }
}
