
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "NoClientCertificateFault", targetNamespace = "urn:internalvim25")
public class NoClientCertificateFaultMsg extends Exception {

    private com.vmware.vim25.NoClientCertificate faultInfo;

    public NoClientCertificateFaultMsg() {
        super();
    }

    public NoClientCertificateFaultMsg(String message) {
        super(message);
    }

    public NoClientCertificateFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoClientCertificateFaultMsg(String message, com.vmware.vim25.NoClientCertificate noClientCertificateFault) {
        super(message);
        this.faultInfo = noClientCertificateFault;
    }

    public NoClientCertificateFaultMsg(String message, com.vmware.vim25.NoClientCertificate noClientCertificateFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = noClientCertificateFault;
    }

    public com.vmware.vim25.NoClientCertificate getFaultInfo() {
        return this.faultInfo;
    }
}
