
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "NoDiskFoundFault", targetNamespace = "urn:internalvim25")
public class NoDiskFoundFaultMsg extends Exception {

    private com.vmware.vim25.NoDiskFound faultInfo;

    public NoDiskFoundFaultMsg() {
        super();
    }

    public NoDiskFoundFaultMsg(String message) {
        super(message);
    }

    public NoDiskFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoDiskFoundFaultMsg(String message, com.vmware.vim25.NoDiskFound noDiskFoundFault) {
        super(message);
        this.faultInfo = noDiskFoundFault;
    }

    public NoDiskFoundFaultMsg(String message, com.vmware.vim25.NoDiskFound noDiskFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = noDiskFoundFault;
    }

    public com.vmware.vim25.NoDiskFound getFaultInfo() {
        return this.faultInfo;
    }
}
