
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "NoDiskSpaceFault", targetNamespace = "urn:internalvim25")
public class NoDiskSpaceFaultMsg extends Exception {

    private com.vmware.vim25.NoDiskSpace faultInfo;

    public NoDiskSpaceFaultMsg() {
        super();
    }

    public NoDiskSpaceFaultMsg(String message) {
        super(message);
    }

    public NoDiskSpaceFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoDiskSpaceFaultMsg(String message, com.vmware.vim25.NoDiskSpace noDiskSpaceFault) {
        super(message);
        this.faultInfo = noDiskSpaceFault;
    }

    public NoDiskSpaceFaultMsg(String message, com.vmware.vim25.NoDiskSpace noDiskSpaceFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = noDiskSpaceFault;
    }

    public com.vmware.vim25.NoDiskSpace getFaultInfo() {
        return this.faultInfo;
    }
}
