
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "NoSubjectNameFault", targetNamespace = "urn:internalvim25")
public class NoSubjectNameFaultMsg extends Exception {

    private com.vmware.vim25.NoSubjectName faultInfo;

    public NoSubjectNameFaultMsg() {
        super();
    }

    public NoSubjectNameFaultMsg(String message) {
        super(message);
    }

    public NoSubjectNameFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoSubjectNameFaultMsg(String message, com.vmware.vim25.NoSubjectName noSubjectNameFault) {
        super(message);
        this.faultInfo = noSubjectNameFault;
    }

    public NoSubjectNameFaultMsg(String message, com.vmware.vim25.NoSubjectName noSubjectNameFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = noSubjectNameFault;
    }

    public com.vmware.vim25.NoSubjectName getFaultInfo() {
        return this.faultInfo;
    }
}
