
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "NotFoundFault", targetNamespace = "urn:internalvim25")
public class NotFoundFaultMsg extends Exception {

    private com.vmware.vim25.NotFound faultInfo;

    public NotFoundFaultMsg() {
        super();
    }

    public NotFoundFaultMsg(String message) {
        super(message);
    }

    public NotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NotFoundFaultMsg(String message, com.vmware.vim25.NotFound notFoundFault) {
        super(message);
        this.faultInfo = notFoundFault;
    }

    public NotFoundFaultMsg(String message, com.vmware.vim25.NotFound notFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = notFoundFault;
    }

    public com.vmware.vim25.NotFound getFaultInfo() {
        return this.faultInfo;
    }
}
