
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "NotSupportedFault", targetNamespace = "urn:internalvim25")
public class NotSupportedFaultMsg extends Exception {

    private com.vmware.vim25.NotSupported faultInfo;

    public NotSupportedFaultMsg() {
        super();
    }

    public NotSupportedFaultMsg(String message) {
        super(message);
    }

    public NotSupportedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NotSupportedFaultMsg(String message, com.vmware.vim25.NotSupported notSupportedFault) {
        super(message);
        this.faultInfo = notSupportedFault;
    }

    public NotSupportedFaultMsg(String message, com.vmware.vim25.NotSupported notSupportedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = notSupportedFault;
    }

    public com.vmware.vim25.NotSupported getFaultInfo() {
        return this.faultInfo;
    }
}
