
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "OutOfBoundsFault", targetNamespace = "urn:internalvim25")
public class OutOfBoundsFaultMsg extends Exception {

    private com.vmware.vim25.OutOfBounds faultInfo;

    public OutOfBoundsFaultMsg() {
        super();
    }

    public OutOfBoundsFaultMsg(String message) {
        super(message);
    }

    public OutOfBoundsFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public OutOfBoundsFaultMsg(String message, com.vmware.vim25.OutOfBounds outOfBoundsFault) {
        super(message);
        this.faultInfo = outOfBoundsFault;
    }

    public OutOfBoundsFaultMsg(String message, com.vmware.vim25.OutOfBounds outOfBoundsFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = outOfBoundsFault;
    }

    public com.vmware.vim25.OutOfBounds getFaultInfo() {
        return this.faultInfo;
    }
}
