
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "PatchNotApplicableFault", targetNamespace = "urn:internalvim25")
public class PatchNotApplicableFaultMsg extends Exception {

    private com.vmware.vim25.PatchNotApplicable faultInfo;

    public PatchNotApplicableFaultMsg() {
        super();
    }

    public PatchNotApplicableFaultMsg(String message) {
        super(message);
    }

    public PatchNotApplicableFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PatchNotApplicableFaultMsg(String message, com.vmware.vim25.PatchNotApplicable patchNotApplicableFault) {
        super(message);
        this.faultInfo = patchNotApplicableFault;
    }

    public PatchNotApplicableFaultMsg(String message, com.vmware.vim25.PatchNotApplicable patchNotApplicableFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = patchNotApplicableFault;
    }

    public com.vmware.vim25.PatchNotApplicable getFaultInfo() {
        return this.faultInfo;
    }
}
