
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "PatchInstallFailedFault", targetNamespace = "urn:internalvim25")
public class PatchInstallFailedFaultMsg extends Exception {

    private com.vmware.vim25.PatchInstallFailed faultInfo;

    public PatchInstallFailedFaultMsg() {
        super();
    }

    public PatchInstallFailedFaultMsg(String message) {
        super(message);
    }

    public PatchInstallFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PatchInstallFailedFaultMsg(String message, com.vmware.vim25.PatchInstallFailed patchInstallFailedFault) {
        super(message);
        this.faultInfo = patchInstallFailedFault;
    }

    public PatchInstallFailedFaultMsg(String message, com.vmware.vim25.PatchInstallFailed patchInstallFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = patchInstallFailedFault;
    }

    public com.vmware.vim25.PatchInstallFailed getFaultInfo() {
        return this.faultInfo;
    }
}
