
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "PatchBinariesNotFoundFault", targetNamespace = "urn:internalvim25")
public class PatchBinariesNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.PatchBinariesNotFound faultInfo;

    public PatchBinariesNotFoundFaultMsg() {
        super();
    }

    public PatchBinariesNotFoundFaultMsg(String message) {
        super(message);
    }

    public PatchBinariesNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PatchBinariesNotFoundFaultMsg(String message, com.vmware.vim25.PatchBinariesNotFound patchBinariesNotFoundFault) {
        super(message);
        this.faultInfo = patchBinariesNotFoundFault;
    }

    public PatchBinariesNotFoundFaultMsg(String message, com.vmware.vim25.PatchBinariesNotFound patchBinariesNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = patchBinariesNotFoundFault;
    }

    public com.vmware.vim25.PatchBinariesNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
