
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "PatchMetadataInvalidFault", targetNamespace = "urn:internalvim25")
public class PatchMetadataInvalidFaultMsg extends Exception {

    private com.vmware.vim25.PatchMetadataInvalid faultInfo;

    public PatchMetadataInvalidFaultMsg() {
        super();
    }

    public PatchMetadataInvalidFaultMsg(String message) {
        super(message);
    }

    public PatchMetadataInvalidFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PatchMetadataInvalidFaultMsg(String message, com.vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault) {
        super(message);
        this.faultInfo = patchMetadataInvalidFault;
    }

    public PatchMetadataInvalidFaultMsg(String message, com.vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = patchMetadataInvalidFault;
    }

    public com.vmware.vim25.PatchMetadataInvalid getFaultInfo() {
        return this.faultInfo;
    }
}
