
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "PlatformConfigFaultFault", targetNamespace = "urn:internalvim25")
public class PlatformConfigFaultFaultMsg extends Exception {

    private com.vmware.vim25.PlatformConfigFault faultInfo;

    public PlatformConfigFaultFaultMsg() {
        super();
    }

    public PlatformConfigFaultFaultMsg(String message) {
        super(message);
    }

    public PlatformConfigFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PlatformConfigFaultFaultMsg(String message, com.vmware.vim25.PlatformConfigFault platformConfigFaultFault) {
        super(message);
        this.faultInfo = platformConfigFaultFault;
    }

    public PlatformConfigFaultFaultMsg(String message, com.vmware.vim25.PlatformConfigFault platformConfigFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = platformConfigFaultFault;
    }

    public com.vmware.vim25.PlatformConfigFault getFaultInfo() {
        return this.faultInfo;
    }
}
