
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ProfileUpdateFailedFault", targetNamespace = "urn:internalvim25")
public class ProfileUpdateFailedFaultMsg extends Exception {

    private com.vmware.vim25.ProfileUpdateFailed faultInfo;

    public ProfileUpdateFailedFaultMsg() {
        super();
    }

    public ProfileUpdateFailedFaultMsg(String message) {
        super(message);
    }

    public ProfileUpdateFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ProfileUpdateFailedFaultMsg(String message, com.vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault) {
        super(message);
        this.faultInfo = profileUpdateFailedFault;
    }

    public ProfileUpdateFailedFaultMsg(String message, com.vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = profileUpdateFailedFault;
    }

    public com.vmware.vim25.ProfileUpdateFailed getFaultInfo() {
        return this.faultInfo;
    }
}
