
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "RebootRequiredFault", targetNamespace = "urn:internalvim25")
public class RebootRequiredFaultMsg extends Exception {

    private com.vmware.vim25.RebootRequired faultInfo;

    public RebootRequiredFaultMsg() {
        super();
    }

    public RebootRequiredFaultMsg(String message) {
        super(message);
    }

    public RebootRequiredFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RebootRequiredFaultMsg(String message, com.vmware.vim25.RebootRequired rebootRequiredFault) {
        super(message);
        this.faultInfo = rebootRequiredFault;
    }

    public RebootRequiredFaultMsg(String message, com.vmware.vim25.RebootRequired rebootRequiredFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = rebootRequiredFault;
    }

    public com.vmware.vim25.RebootRequired getFaultInfo() {
        return this.faultInfo;
    }
}
