
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "RecordReplayDisabledFault", targetNamespace = "urn:internalvim25")
public class RecordReplayDisabledFaultMsg extends Exception {

    private com.vmware.vim25.RecordReplayDisabled faultInfo;

    public RecordReplayDisabledFaultMsg() {
        super();
    }

    public RecordReplayDisabledFaultMsg(String message) {
        super(message);
    }

    public RecordReplayDisabledFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RecordReplayDisabledFaultMsg(String message, com.vmware.vim25.RecordReplayDisabled recordReplayDisabledFault) {
        super(message);
        this.faultInfo = recordReplayDisabledFault;
    }

    public RecordReplayDisabledFaultMsg(String message, com.vmware.vim25.RecordReplayDisabled recordReplayDisabledFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = recordReplayDisabledFault;
    }

    public com.vmware.vim25.RecordReplayDisabled getFaultInfo() {
        return this.faultInfo;
    }
}
