
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "RemoveFailedFault", targetNamespace = "urn:internalvim25")
public class RemoveFailedFaultMsg extends Exception {

    private com.vmware.vim25.RemoveFailed faultInfo;

    public RemoveFailedFaultMsg() {
        super();
    }

    public RemoveFailedFaultMsg(String message) {
        super(message);
    }

    public RemoveFailedFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RemoveFailedFaultMsg(String message, com.vmware.vim25.RemoveFailed removeFailedFault) {
        super(message);
        this.faultInfo = removeFailedFault;
    }

    public RemoveFailedFaultMsg(String message, com.vmware.vim25.RemoveFailed removeFailedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = removeFailedFault;
    }

    public com.vmware.vim25.RemoveFailed getFaultInfo() {
        return this.faultInfo;
    }
}
