
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "RequestCanceledFault", targetNamespace = "urn:internalvim25")
public class RequestCanceledFaultMsg extends Exception {

    private com.vmware.vim25.RequestCanceled faultInfo;

    public RequestCanceledFaultMsg() {
        super();
    }

    public RequestCanceledFaultMsg(String message) {
        super(message);
    }

    public RequestCanceledFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RequestCanceledFaultMsg(String message, com.vmware.vim25.RequestCanceled requestCanceledFault) {
        super(message);
        this.faultInfo = requestCanceledFault;
    }

    public RequestCanceledFaultMsg(String message, com.vmware.vim25.RequestCanceled requestCanceledFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = requestCanceledFault;
    }

    public com.vmware.vim25.RequestCanceled getFaultInfo() {
        return this.faultInfo;
    }
}
