
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ResourceInUseFault", targetNamespace = "urn:internalvim25")
public class ResourceInUseFaultMsg extends Exception {

    private com.vmware.vim25.ResourceInUse faultInfo;

    public ResourceInUseFaultMsg() {
        super();
    }

    public ResourceInUseFaultMsg(String message) {
        super(message);
    }

    public ResourceInUseFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ResourceInUseFaultMsg(String message, com.vmware.vim25.ResourceInUse resourceInUseFault) {
        super(message);
        this.faultInfo = resourceInUseFault;
    }

    public ResourceInUseFaultMsg(String message, com.vmware.vim25.ResourceInUse resourceInUseFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = resourceInUseFault;
    }

    public com.vmware.vim25.ResourceInUse getFaultInfo() {
        return this.faultInfo;
    }
}
