
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ResourceNotAvailableFault", targetNamespace = "urn:internalvim25")
public class ResourceNotAvailableFaultMsg extends Exception {

    private com.vmware.vim25.ResourceNotAvailable faultInfo;

    public ResourceNotAvailableFaultMsg() {
        super();
    }

    public ResourceNotAvailableFaultMsg(String message) {
        super(message);
    }

    public ResourceNotAvailableFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ResourceNotAvailableFaultMsg(String message, com.vmware.vim25.ResourceNotAvailable resourceNotAvailableFault) {
        super(message);
        this.faultInfo = resourceNotAvailableFault;
    }

    public ResourceNotAvailableFaultMsg(String message, com.vmware.vim25.ResourceNotAvailable resourceNotAvailableFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = resourceNotAvailableFault;
    }

    public com.vmware.vim25.ResourceNotAvailable getFaultInfo() {
        return this.faultInfo;
    }
}
