
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "RollbackFailureFault", targetNamespace = "urn:internalvim25")
public class RollbackFailureFaultMsg extends Exception {

    private com.vmware.vim25.RollbackFailure faultInfo;

    public RollbackFailureFaultMsg() {
        super();
    }

    public RollbackFailureFaultMsg(String message) {
        super(message);
    }

    public RollbackFailureFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RollbackFailureFaultMsg(String message, com.vmware.vim25.RollbackFailure rollbackFailureFault) {
        super(message);
        this.faultInfo = rollbackFailureFault;
    }

    public RollbackFailureFaultMsg(String message, com.vmware.vim25.RollbackFailure rollbackFailureFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = rollbackFailureFault;
    }

    public com.vmware.vim25.RollbackFailure getFaultInfo() {
        return this.faultInfo;
    }
}
