
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "RuntimeFaultFault", targetNamespace = "urn:internalvim25")
public class RuntimeFaultFaultMsg extends Exception {

    private com.vmware.vim25.RuntimeFault faultInfo;

    public RuntimeFaultFaultMsg() {
        super();
    }

    public RuntimeFaultFaultMsg(String message) {
        super(message);
    }

    public RuntimeFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RuntimeFaultFaultMsg(String message, com.vmware.vim25.RuntimeFault runtimeFaultFault) {
        super(message);
        this.faultInfo = runtimeFaultFault;
    }

    public RuntimeFaultFaultMsg(String message, com.vmware.vim25.RuntimeFault runtimeFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = runtimeFaultFault;
    }

    public com.vmware.vim25.RuntimeFault getFaultInfo() {
        return this.faultInfo;
    }
}
