
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "SnapshotFaultFault", targetNamespace = "urn:internalvim25")
public class SnapshotFaultFaultMsg extends Exception {

    private com.vmware.vim25.SnapshotFault faultInfo;

    public SnapshotFaultFaultMsg() {
        super();
    }

    public SnapshotFaultFaultMsg(String message) {
        super(message);
    }

    public SnapshotFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SnapshotFaultFaultMsg(String message, com.vmware.vim25.SnapshotFault snapshotFaultFault) {
        super(message);
        this.faultInfo = snapshotFaultFault;
    }

    public SnapshotFaultFaultMsg(String message, com.vmware.vim25.SnapshotFault snapshotFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = snapshotFaultFault;
    }

    public com.vmware.vim25.SnapshotFault getFaultInfo() {
        return this.faultInfo;
    }
}
