
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "SSLVerifyFaultFault", targetNamespace = "urn:internalvim25")
public class SSLVerifyFaultFaultMsg extends Exception {

    private com.vmware.vim25.SSLVerifyFault faultInfo;

    public SSLVerifyFaultFaultMsg() {
        super();
    }

    public SSLVerifyFaultFaultMsg(String message) {
        super(message);
    }

    public SSLVerifyFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SSLVerifyFaultFaultMsg(String message, com.vmware.vim25.SSLVerifyFault sslVerifyFaultFault) {
        super(message);
        this.faultInfo = sslVerifyFaultFault;
    }

    public SSLVerifyFaultFaultMsg(String message, com.vmware.vim25.SSLVerifyFault sslVerifyFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = sslVerifyFaultFault;
    }

    public com.vmware.vim25.SSLVerifyFault getFaultInfo() {
        return this.faultInfo;
    }
}
