
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "SSPIChallengeFault", targetNamespace = "urn:internalvim25")
public class SSPIChallengeFaultMsg extends Exception {

    private com.vmware.vim25.SSPIChallenge faultInfo;

    public SSPIChallengeFaultMsg() {
        super();
    }

    public SSPIChallengeFaultMsg(String message) {
        super(message);
    }

    public SSPIChallengeFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SSPIChallengeFaultMsg(String message, com.vmware.vim25.SSPIChallenge sspiChallengeFault) {
        super(message);
        this.faultInfo = sspiChallengeFault;
    }

    public SSPIChallengeFaultMsg(String message, com.vmware.vim25.SSPIChallenge sspiChallengeFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = sspiChallengeFault;
    }

    public com.vmware.vim25.SSPIChallenge getFaultInfo() {
        return this.faultInfo;
    }
}
