
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "SystemErrorFault", targetNamespace = "urn:internalvim25")
public class SystemErrorFaultMsg extends Exception {

    private com.vmware.vim25.SystemError faultInfo;

    public SystemErrorFaultMsg() {
        super();
    }

    public SystemErrorFaultMsg(String message) {
        super(message);
    }

    public SystemErrorFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SystemErrorFaultMsg(String message, com.vmware.vim25.SystemError systemErrorFault) {
        super(message);
        this.faultInfo = systemErrorFault;
    }

    public SystemErrorFaultMsg(String message, com.vmware.vim25.SystemError systemErrorFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = systemErrorFault;
    }

    public com.vmware.vim25.SystemError getFaultInfo() {
        return this.faultInfo;
    }
}
