
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "TaskInProgressFault", targetNamespace = "urn:internalvim25")
public class TaskInProgressFaultMsg extends Exception {

    private com.vmware.vim25.TaskInProgress faultInfo;

    public TaskInProgressFaultMsg() {
        super();
    }

    public TaskInProgressFaultMsg(String message) {
        super(message);
    }

    public TaskInProgressFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TaskInProgressFaultMsg(String message, com.vmware.vim25.TaskInProgress taskInProgressFault) {
        super(message);
        this.faultInfo = taskInProgressFault;
    }

    public TaskInProgressFaultMsg(String message, com.vmware.vim25.TaskInProgress taskInProgressFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = taskInProgressFault;
    }

    public com.vmware.vim25.TaskInProgress getFaultInfo() {
        return this.faultInfo;
    }
}
