
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "TimedoutFault", targetNamespace = "urn:internalvim25")
public class TimedoutFaultMsg extends Exception {

    private com.vmware.vim25.Timedout faultInfo;

    public TimedoutFaultMsg() {
        super();
    }

    public TimedoutFaultMsg(String message) {
        super(message);
    }

    public TimedoutFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TimedoutFaultMsg(String message, com.vmware.vim25.Timedout timedoutFault) {
        super(message);
        this.faultInfo = timedoutFault;
    }

    public TimedoutFaultMsg(String message, com.vmware.vim25.Timedout timedoutFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = timedoutFault;
    }

    public com.vmware.vim25.Timedout getFaultInfo() {
        return this.faultInfo;
    }
}
