
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "ToolsUnavailableFault", targetNamespace = "urn:internalvim25")
public class ToolsUnavailableFaultMsg extends Exception {

    private com.vmware.vim25.ToolsUnavailable faultInfo;

    public ToolsUnavailableFaultMsg() {
        super();
    }

    public ToolsUnavailableFaultMsg(String message) {
        super(message);
    }

    public ToolsUnavailableFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ToolsUnavailableFaultMsg(String message, com.vmware.vim25.ToolsUnavailable toolsUnavailableFault) {
        super(message);
        this.faultInfo = toolsUnavailableFault;
    }

    public ToolsUnavailableFaultMsg(String message, com.vmware.vim25.ToolsUnavailable toolsUnavailableFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = toolsUnavailableFault;
    }

    public com.vmware.vim25.ToolsUnavailable getFaultInfo() {
        return this.faultInfo;
    }
}
