
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "TooManyHostsFault", targetNamespace = "urn:internalvim25")
public class TooManyHostsFaultMsg extends Exception {

    private com.vmware.vim25.TooManyHosts faultInfo;

    public TooManyHostsFaultMsg() {
        super();
    }

    public TooManyHostsFaultMsg(String message) {
        super(message);
    }

    public TooManyHostsFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TooManyHostsFaultMsg(String message, com.vmware.vim25.TooManyHosts tooManyHostsFault) {
        super(message);
        this.faultInfo = tooManyHostsFault;
    }

    public TooManyHostsFaultMsg(String message, com.vmware.vim25.TooManyHosts tooManyHostsFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = tooManyHostsFault;
    }

    public com.vmware.vim25.TooManyHosts getFaultInfo() {
        return this.faultInfo;
    }
}
