
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "UserNotFoundFault", targetNamespace = "urn:internalvim25")
public class UserNotFoundFaultMsg extends Exception {

    private com.vmware.vim25.UserNotFound faultInfo;

    public UserNotFoundFaultMsg() {
        super();
    }

    public UserNotFoundFaultMsg(String message) {
        super(message);
    }

    public UserNotFoundFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UserNotFoundFaultMsg(String message, com.vmware.vim25.UserNotFound userNotFoundFault) {
        super(message);
        this.faultInfo = userNotFoundFault;
    }

    public UserNotFoundFaultMsg(String message, com.vmware.vim25.UserNotFound userNotFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = userNotFoundFault;
    }

    public com.vmware.vim25.UserNotFound getFaultInfo() {
        return this.faultInfo;
    }
}
