
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VAppConfigFaultFault", targetNamespace = "urn:internalvim25")
public class VAppConfigFaultFaultMsg extends Exception {

    private com.vmware.vim25.VAppConfigFault faultInfo;

    public VAppConfigFaultFaultMsg() {
        super();
    }

    public VAppConfigFaultFaultMsg(String message) {
        super(message);
    }

    public VAppConfigFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VAppConfigFaultFaultMsg(String message, com.vmware.vim25.VAppConfigFault vAppConfigFaultFault) {
        super(message);
        this.faultInfo = vAppConfigFaultFault;
    }

    public VAppConfigFaultFaultMsg(String message, com.vmware.vim25.VAppConfigFault vAppConfigFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vAppConfigFaultFault;
    }

    public com.vmware.vim25.VAppConfigFault getFaultInfo() {
        return this.faultInfo;
    }
}
