
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VimFaultFault", targetNamespace = "urn:internalvim25")
public class VimFaultFaultMsg extends Exception {

    private com.vmware.vim25.VimFault faultInfo;

    public VimFaultFaultMsg() {
        super();
    }

    public VimFaultFaultMsg(String message) {
        super(message);
    }

    public VimFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VimFaultFaultMsg(String message, com.vmware.vim25.VimFault vimFaultFault) {
        super(message);
        this.faultInfo = vimFaultFault;
    }

    public VimFaultFaultMsg(String message, com.vmware.vim25.VimFault vimFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vimFaultFault;
    }

    public com.vmware.vim25.VimFault getFaultInfo() {
        return this.faultInfo;
    }
}
