package com.vmware.vim25;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 *
 */
@WebServiceClient(name = "VimService",
                  wsdlLocation = "file:modified_wsdl/vim25/vimService.wsdl",
                  targetNamespace = "urn:internalvim25Service")
public class VimService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("urn:internalvim25Service", "VimService");
    public static final QName VimPort = new QName("urn:internalvim25Service", "VimPort");
    static {
        URL url = null;
        try {
            url = URI.create("file:modified_wsdl/vim25/vimService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VimService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:modified_wsdl/vim25/vimService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VimService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VimService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VimService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VimService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VimService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VimService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VimPortType
     */
    @WebEndpoint(name = "VimPort")
    public VimPortType getVimPort() {
        return super.getPort(VimPort, VimPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VimPortType
     */
    @WebEndpoint(name = "VimPort")
    public VimPortType getVimPort(WebServiceFeature... features) {
        return super.getPort(VimPort, VimPortType.class, features);
    }

}
