
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VmConfigFaultFault", targetNamespace = "urn:internalvim25")
public class VmConfigFaultFaultMsg extends Exception {

    private com.vmware.vim25.VmConfigFault faultInfo;

    public VmConfigFaultFaultMsg() {
        super();
    }

    public VmConfigFaultFaultMsg(String message) {
        super(message);
    }

    public VmConfigFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VmConfigFaultFaultMsg(String message, com.vmware.vim25.VmConfigFault vmConfigFaultFault) {
        super(message);
        this.faultInfo = vmConfigFaultFault;
    }

    public VmConfigFaultFaultMsg(String message, com.vmware.vim25.VmConfigFault vmConfigFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vmConfigFaultFault;
    }

    public com.vmware.vim25.VmConfigFault getFaultInfo() {
        return this.faultInfo;
    }
}
