
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VmFaultToleranceIssueFault", targetNamespace = "urn:internalvim25")
public class VmFaultToleranceIssueFaultMsg extends Exception {

    private com.vmware.vim25.VmFaultToleranceIssue faultInfo;

    public VmFaultToleranceIssueFaultMsg() {
        super();
    }

    public VmFaultToleranceIssueFaultMsg(String message) {
        super(message);
    }

    public VmFaultToleranceIssueFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VmFaultToleranceIssueFaultMsg(String message, com.vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault) {
        super(message);
        this.faultInfo = vmFaultToleranceIssueFault;
    }

    public VmFaultToleranceIssueFaultMsg(String message, com.vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vmFaultToleranceIssueFault;
    }

    public com.vmware.vim25.VmFaultToleranceIssue getFaultInfo() {
        return this.faultInfo;
    }
}
