
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VmfsAmbiguousMountFault", targetNamespace = "urn:internalvim25")
public class VmfsAmbiguousMountFaultMsg extends Exception {

    private com.vmware.vim25.VmfsAmbiguousMount faultInfo;

    public VmfsAmbiguousMountFaultMsg() {
        super();
    }

    public VmfsAmbiguousMountFaultMsg(String message) {
        super(message);
    }

    public VmfsAmbiguousMountFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VmfsAmbiguousMountFaultMsg(String message, com.vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault) {
        super(message);
        this.faultInfo = vmfsAmbiguousMountFault;
    }

    public VmfsAmbiguousMountFaultMsg(String message, com.vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vmfsAmbiguousMountFault;
    }

    public com.vmware.vim25.VmfsAmbiguousMount getFaultInfo() {
        return this.faultInfo;
    }
}
