
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VmToolsUpgradeFaultFault", targetNamespace = "urn:internalvim25")
public class VmToolsUpgradeFaultFaultMsg extends Exception {

    private com.vmware.vim25.VmToolsUpgradeFault faultInfo;

    public VmToolsUpgradeFaultFaultMsg() {
        super();
    }

    public VmToolsUpgradeFaultFaultMsg(String message) {
        super(message);
    }

    public VmToolsUpgradeFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VmToolsUpgradeFaultFaultMsg(String message, com.vmware.vim25.VmToolsUpgradeFault vmToolsUpgradeFaultFault) {
        super(message);
        this.faultInfo = vmToolsUpgradeFaultFault;
    }

    public VmToolsUpgradeFaultFaultMsg(String message, com.vmware.vim25.VmToolsUpgradeFault vmToolsUpgradeFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vmToolsUpgradeFaultFault;
    }

    public com.vmware.vim25.VmToolsUpgradeFault getFaultInfo() {
        return this.faultInfo;
    }
}
