
package com.vmware.vim25;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * Generated source version: 4.1.1
 */

@WebFault(name = "VsanFaultFault", targetNamespace = "urn:internalvim25")
public class VsanFaultFaultMsg extends Exception {

    private com.vmware.vim25.VsanFault faultInfo;

    public VsanFaultFaultMsg() {
        super();
    }

    public VsanFaultFaultMsg(String message) {
        super(message);
    }

    public VsanFaultFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VsanFaultFaultMsg(String message, com.vmware.vim25.VsanFault vsanFaultFault) {
        super(message);
        this.faultInfo = vsanFaultFault;
    }

    public VsanFaultFaultMsg(String message, com.vmware.vim25.VsanFault vsanFaultFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vsanFaultFault;
    }

    public com.vmware.vim25.VsanFault getFaultInfo() {
        return this.faultInfo;
    }
}
